// Code generated by MockGen. DO NOT EDIT.
// Source: commit.go

// Package handlers is a generated GoMock package.
package handlers

import (
	models "repo-metrics/pkg/application/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCommit is a mock of Commit interface.
type MockCommit struct {
	ctrl     *gomock.Controller
	recorder *MockCommitMockRecorder
}

// MockCommitMockRecorder is the mock recorder for MockCommit.
type MockCommitMockRecorder struct {
	mock *MockCommit
}

// NewMockCommit creates a new mock instance.
func NewMockCommit(ctrl *gomock.Controller) *MockCommit {
	mock := &MockCommit{ctrl: ctrl}
	mock.recorder = &MockCommitMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommit) EXPECT() *MockCommitMockRecorder {
	return m.recorder
}

// ActivityScore mocks base method.
func (m *MockCommit) ActivityScore() ([]models.ScoreRepository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivityScore")
	ret0, _ := ret[0].([]models.ScoreRepository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ActivityScore indicates an expected call of ActivityScore.
func (mr *MockCommitMockRecorder) ActivityScore() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivityScore", reflect.TypeOf((*MockCommit)(nil).ActivityScore))
}

// MockWriter is a mock of Writer interface.
type MockWriter struct {
	ctrl     *gomock.Controller
	recorder *MockWriterMockRecorder
}

// MockWriterMockRecorder is the mock recorder for MockWriter.
type MockWriterMockRecorder struct {
	mock *MockWriter
}

// NewMockWriter creates a new mock instance.
func NewMockWriter(ctrl *gomock.Controller) *MockWriter {
	mock := &MockWriter{ctrl: ctrl}
	mock.recorder = &MockWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWriter) EXPECT() *MockWriterMockRecorder {
	return m.recorder
}

// WriteScores mocks base method.
func (m *MockWriter) WriteScores(scores []models.ScoreRepository) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteScores", scores)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteScores indicates an expected call of WriteScores.
func (mr *MockWriterMockRecorder) WriteScores(scores interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteScores", reflect.TypeOf((*MockWriter)(nil).WriteScores), scores)
}
